export const HTTP_MODULE_ID = 'HTTP_MODULE_ID';
export const HTTP_MODULE_OPTIONS = 'HTTP_MODULE_OPTIONS';
export const HTTP_PROVIDER_TOKEN = 'HTTP_PROVIDER_TOKEN';
export const HTTP_PROVIDER_INSTANCE_TOKEN = 'HTTP_PROVIDER_INSTANCE_TOKEN';

export const KY_INSTANCE_TOKEN = 'KY_INSTANCE_TOKEN';
export const AXIOS_INSTANCE_TOKEN = 'AXIOS_INSTANCE_TOKEN';
